---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-web-site-html-pvc
  namespace: web-sites
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

